spring.application.name=sweetshop-backend

spring.data.mongodb.uri=mongodb+srv://sweetuser:siddhant@cluster0.laora6g.mongodb.net/sweetshopdb
spring.data.mongodb.database=sweetshopdb

server.port=8080

# JWT
jwt.secret=f3b2d6c1a4e7c8f9a0b1c2d3e4f5g6h9f3b2d6c1a4e7c8f
jwt.expirationMs=86400000
