spring.application.name=sweetshop-backend

spring.data.mongodb.uri=mongodb+srv://sweetuser:siddhant@cluster0.laora6g.mongodb.net/sweetshopdb
spring.data.mongodb.database=sweetshopdb

server.port=8080
